window.FOREST = {
    "url_gateway": "/forestWS/",
    "url_gateway_forest": "https://alcaldiadevcaliforest5.forestbpms.co/forestWS/",
    "client_id": "Tg3w18tN9PNOEGVpiMLXJPhkkjoa",
    "client_secret": "EQDwZaO1ZnsZrVoU9CI6xHraunka",
    "urlDirectorioServicios": "https://alcaldiadevcaliforest5.forestbpms.co/api/am/store/v0.14/apis",
    "url_pub": "https://alcaldiadevcaliforest5.forestbpms.co/",
    "url_formas_contexto": "xuiForms",
    "downloads_notify": "https://alcaldiadevcaliforest5.forestbpms.co/downloads/forestNotify5/notify.jnlp",
    "downloads_scanner": "https://alcaldiadevcaliforest5.forestbpms.co/downloads/forestScanner.exe",
    "downloads_ms": "https://alcaldiadevcaliforest5.forestbpms.co/downloads/Forest_BPMS_Components.exe",
    "url_resources": "/resources",
    "theme": "vista",
    "build_timestamp": "2018-08-21 14:52:26 COT",
    "app_name": "FOREST BPM : Modelo Integral de Respuesta Amigable, Versátil y Eficaz",
    "google_data_sitekey": "6Lf3U2IUAAAAAFS_I5nMkttK2_vDbdRtoBARgbAh",
    "context_menu": "/workplaceServicesComponent/0.0.1/api/work-place/listWorkplaceMenu?_rnd_=",
    "urlCaracterizador": "https://alcaldiadevcaliforest5.forestbpms.co/resources/caracterizador/",
    "urlMediosMagneticos": "https://alcaldiadevcaliforest5.forestbpms.co/FormulariosQAS/FrontController?service=AutodeclaracionService&action=validateFormNumber&data=",
    "urlMediosMagneticosa": "http://servicios.cali.gov.co:9292/FormulariosAD/FrontController?service=AutodeclaracionService&action=validateFormNumber&data=",
    "url_inicioSesion": "https://alcaldiadevcaliforest5.forestbpms.co/forestWS/workplaceServicesComponent/0.0.1/api/work-place/iniciarSesion",
    "maxPageSize": "250",
    "scope": "openid users_system",
    "url_contexto_calendario": "forest/config/1.0.0/api/for-cfg-festivos/findByYear/",
    "context_menu_report": "report-viewer/1.0.0/consultarMisReportes"
};